### ISSUE TITLE
Cron-based DB backups to s3

### ISSUE THREAD

**Issue by Flamefork** [creative-co/mana#12]

**Comment by antlypls** [comment]
Any progress on it?

**Comment by pavel-rosputko** [comment]
To use:
- add `set :aws, access_key_id:'...', secret_access_key: '...'` in `config/deploy.rb`
- add `recipe[railsapp::backup]` in `set :run_list`

**Comment by Flamefork** [comment]
Please add all this configuration to default `deploy.rb`, with meaningful comments like other "must-set" options.
Db backup is something we want to force for every project, at least by making it a default option.

**Comment by Flamefork** [comment]
Great! Thank you!
